### ISSUE TITLE
help section shows Lorem ipsum

### ISSUE THREAD

**Issue by KarimAbdelatty** [KarimAbdelatty/IDel#12]

**Comment by KarimAbdelatty** [comment]
I'm assigning this to you as the help contents are being populated from the server.
in HelpActivity.java
`private void fetchHelp() {

        HashMap<String, String> urlParams = new HashMap<>();
        urlParams.put("id", tempHelpBean.getId());

/*        if (isLoadMore) {
            urlParams.put("page", String.valueOf(currentPage + 1));
        }*/

        DataManager.fetchHelp(urlParams, new HelpListener() {
            @Override
            public void onLoadCompleted(HelpBean helpBeanWS) {

                helpBean = helpBeanWS;
                populateHelp();

            }

            @Override
            public void onLoadFailed(String error) {
                Snackbar.make(coordinatorLayout, error, Snackbar.LENGTH_INDEFINITE)
                        .setAction(R.string.btn_retry, snackBarRefreshOnClickListener).show();
                swipeView.setRefreshing(false);
                setProgressScreenVisibility(true, false);
                if (App.getInstance().isDemo()) {
                    helpBean = new HelpBean();
                    helpBean.setId(tempHelpBean.getId());
                    helpBean.setHelpful(true);
                    helpBean.setTitle(tempHelpBean.getTitle());
                    helpBean.setContent(getString(R.string.sample_lorem_ipsum_large));
                    helpBean.setIcon(tempHelpBean.getIcon());
                    populateHelp();
                }
            }
        });

    }`

**Comment by KarimAbdelatty** [comment]
![screenshot_20180617-144441](https://user-images.githubusercontent.com/23244706/41511016-1c1b2906-723d-11e8-99d8-c8535de330a9.jpg)

**Comment by Mohamed-Amr** [comment]
Yes, it is. We need to set the proper text to these fields and insert them into the database. I believe there is some standard we can follow.

**Comment by KarimAbdelatty** [comment]
for now, replace lorem ipsum with "More Information Soon"

**Comment by Mohamed-Amr** [comment]
Fixed.
