### ISSUE TITLE
Should we login with mobile number instead of email?

### ISSUE THREAD

**Issue by KarimAbdelatty** [KarimAbdelatty/IDel#5]
Not all drivers have an email, in similar apps, mobile number is the user ID.

**Comment by Mohamed-Amr** [comment]
Currently, it is not implemented. If you think it is that important I can do it.

**Comment by KarimAbdelatty** [comment]
Also we will need this implemented on wedel as well

**Comment by Mohamed-Amr** [comment]
Sure

**Comment by KarimAbdelatty** [comment]
done
