### ISSUE TITLE
Can't login after logging out from the app, Also can't reset, can't create a new account with the same mobile number

### ISSUE THREAD

**Issue by KarimAbdelatty** [KarimAbdelatty/IDel#6]
Can't login after logging out from the app:
{"status":"error","message":"Unknown Credential! Try Again","error":"202"}

Can't reset: 
{"status":"error","message":"Sorry. Please Enter Your Correct Email."}

Can't create a new account with the same mobile number:
response:    {"status":"success","data":{"phone":"+15409984421","is_available":false}}

**Comment by Mohamed-Amr** [comment]
Again, I don't have this problem with my driver account.
dodo@gmail.com
ultimate

Remember, you have entered "karim@vt.edu22" as your email. I'm sure you are trying with your correct email. I have edited that for you. It should now work with your correct email: karim@vt.edu
log using the same password.
That is also the reason why you weren't able to reset.
